name: Rocq Ditto CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rocq-version: ["9.1.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Install opam (no switch)
        run: |
          sudo apt update
          sudo apt install -y opam
          opam init -y --bare
          eval "$(opam env)"

      - name: Cache local opam switch
        uses: actions/cache@v4
        with:
          path: _opam
          key: opam-local-${{ matrix.rocq-version }}-${{ hashFiles('dune-project', '**/*.opam', 'configure.sh') }}
          restore-keys: opam-local-
          
      - name: Configure Rocq-ditto
        run: |
          set -eux
          ./configure.sh ${{ matrix.rocq-version }}
          eval "$(opam env)"

      - name: Build Rocq-ditto
        run:
          eval "$(opam env --switch=./)"
          dune build

